version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MESSAGE: "Hello world from Docker Compose!"
  
  prometheus:
    image: prom/prometheus:v2.53.2
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"

networks:
  default:
    name: flask-app-network
    driver: bridge